export const hC = [
  {
    id: "tally",
    name: "Tally Prime",
    category: "finance",
    industries: ["accounting", "retail", "manufacturing"],
    avgFileSizeMB: 200,
    dataGrowth: "medium",
    monthlyGrowthGB: 1.5,
    backupIntervalMin: 30,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup", "fast-restore"],
    synonyms: ["tally", "tallyprime", "tally erp"],
  },
  {
    id: "busy",
    name: "Busy Accounting",
    category: "finance",
    industries: ["accounting", "retail"],
    avgFileSizeMB: 150,
    dataGrowth: "medium",
    monthlyGrowthGB: 1.2,
    backupIntervalMin: 30,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup"],
    synonyms: ["busy"],
  },
  {
    id: "quickbooks",
    name: "QuickBooks",
    category: "finance",
    industries: ["accounting", "retail"],
    avgFileSizeMB: 300,
    dataGrowth: "medium",
    monthlyGrowthGB: 1.5,
    backupIntervalMin: 30,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup"],
    synonyms: ["quickbooks", "qb"],
  },
  {
    id: "zohobooks",
    name: "Zoho Books",
    category: "finance",
    industries: ["accounting"],
    avgFileSizeMB: 50,
    dataGrowth: "low",
    monthlyGrowthGB: 0.6,
    backupIntervalMin: 60,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "high",
    synonyms: ["zoho books", "zoho"],
  },
  {
    id: "marg",
    name: "Marg ERP",
    category: "finance",
    industries: ["accounting", "retail", "healthcare"],
    avgFileSizeMB: 180,
    dataGrowth: "medium",
    monthlyGrowthGB: 1.3,
    backupIntervalMin: 30,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup"],
    synonyms: ["marg"],
  },
  {
    id: "sage",
    name: "Sage",
    category: "finance",
    industries: ["accounting", "manufacturing"],
    avgFileSizeMB: 250,
    dataGrowth: "medium",
    monthlyGrowthGB: 1.4,
    backupIntervalMin: 30,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup"],
    synonyms: ["sage"],
  },
  {
    id: "vyapar",
    name: "Vyapar",
    category: "finance",
    industries: ["retail", "accounting"],
    avgFileSizeMB: 40,
    dataGrowth: "low",
    monthlyGrowthGB: 0.5,
    backupIntervalMin: 60,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "high",
    synonyms: ["vyapar"],
  },
  {
    id: "sap",
    name: "SAP",
    category: "erp",
    industries: ["manufacturing", "accounting", "government"],
    avgFileSizeMB: 2e3,
    dataGrowth: "very-high",
    monthlyGrowthGB: 8,
    backupIntervalMin: 15,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup", "fast-restore"],
    synonyms: ["sap", "s/4hana", "hana"],
  },
  {
    id: "oracle-erp",
    name: "Oracle ERP",
    category: "erp",
    industries: ["manufacturing", "government"],
    avgFileSizeMB: 2e3,
    dataGrowth: "very-high",
    monthlyGrowthGB: 7,
    backupIntervalMin: 15,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup"],
    synonyms: ["oracle erp", "oracle fusion"],
  },
  {
    id: "erpnext",
    name: "ERPNext",
    category: "erp",
    industries: ["manufacturing", "retail"],
    avgFileSizeMB: 500,
    dataGrowth: "high",
    monthlyGrowthGB: 3,
    backupIntervalMin: 30,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup"],
    synonyms: ["erpnext", "frappe"],
  },
  {
    id: "salesforce",
    name: "Salesforce (local exports)",
    category: "erp",
    industries: ["retail", "software", "other"],
    avgFileSizeMB: 300,
    dataGrowth: "medium",
    monthlyGrowthGB: 2,
    backupIntervalMin: 1440,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "high",
    synonyms: ["salesforce", "crm"],
  },
  {
    id: "excel",
    name: "Excel",
    category: "office",
    industries: [
      "accounting",
      "manufacturing",
      "other",
      "government",
      "retail",
    ],
    avgFileSizeMB: 15,
    dataGrowth: "low",
    monthlyGrowthGB: 0.5,
    backupIntervalMin: 60,
    compressibility: "high",
    dedupBenefit: "very-high",
    versioning: !0,
    priority: "high",
    synonyms: ["excel", "spreadsheet", "xlsx"],
  },
  {
    id: "msoffice",
    name: "MS Office",
    category: "office",
    industries: ["accounting", "legal", "education", "other", "government"],
    avgFileSizeMB: 12,
    dataGrowth: "low",
    monthlyGrowthGB: 0.6,
    backupIntervalMin: 60,
    compressibility: "high",
    dedupBenefit: "very-high",
    versioning: !0,
    priority: "high",
    synonyms: ["ms office", "microsoft office", "word", "powerpoint", "docx"],
  },
  {
    id: "pdf-archive",
    name: "PDF Archives",
    category: "office",
    industries: ["legal", "accounting", "government", "healthcare"],
    avgFileSizeMB: 8,
    dataGrowth: "low",
    monthlyGrowthGB: 0.8,
    backupIntervalMin: 1440,
    compressibility: "low",
    dedupBenefit: "medium",
    versioning: !1,
    priority: "high",
    specialNeeds: ["compliance-archive"],
    synonyms: ["pdf", "pdf archive", "documents"],
  },
  {
    id: "zip",
    name: "ZIP Archives",
    category: "office",
    industries: ["other", "software", "government"],
    avgFileSizeMB: 500,
    dataGrowth: "medium",
    monthlyGrowthGB: 2,
    backupIntervalMin: 1440,
    compressibility: "low",
    dedupBenefit: "low",
    versioning: !1,
    priority: "medium",
    synonyms: ["zip file", "rar file", ".zip"],
  },
  {
    id: "msaccess",
    name: "MS Access",
    category: "database",
    industries: ["accounting", "other", "government"],
    avgFileSizeMB: 400,
    dataGrowth: "medium",
    monthlyGrowthGB: 1.5,
    backupIntervalMin: 60,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "high",
    specialNeeds: ["db-aware-backup"],
    synonyms: ["access", "ms access", "mdb"],
  },
  {
    id: "outlook",
    name: "Outlook (PST/OST)",
    category: "email",
    industries: ["accounting", "legal", "other", "government"],
    avgFileSizeMB: 5e3,
    dataGrowth: "medium",
    monthlyGrowthGB: 2,
    backupIntervalMin: 60,
    compressibility: "medium",
    dedupBenefit: "very-high",
    versioning: !0,
    priority: "high",
    specialNeeds: ["email-journaling"],
    synonyms: ["outlook", "pst", "ost"],
  },
  {
    id: "workspace",
    name: "Gmail / Google Workspace",
    category: "email",
    industries: ["software", "education", "other"],
    avgFileSizeMB: 3e3,
    dataGrowth: "medium",
    monthlyGrowthGB: 2,
    backupIntervalMin: 1440,
    compressibility: "medium",
    dedupBenefit: "very-high",
    versioning: !0,
    priority: "high",
    specialNeeds: ["email-journaling"],
    synonyms: ["gmail", "google workspace", "gsuite"],
  },
  {
    id: "whatsapp-biz",
    name: "WhatsApp Business Exports",
    category: "email",
    industries: ["retail", "hospitality", "other"],
    avgFileSizeMB: 1200,
    dataGrowth: "medium",
    monthlyGrowthGB: 1.5,
    backupIntervalMin: 1440,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !1,
    priority: "medium",
    synonyms: ["whatsapp", "whatsapp business"],
  },
  {
    id: "photoshop",
    name: "Adobe Photoshop",
    category: "design",
    industries: ["photography", "media", "architecture"],
    avgFileSizeMB: 300,
    dataGrowth: "high",
    monthlyGrowthGB: 6,
    backupIntervalMin: 60,
    compressibility: "low",
    dedupBenefit: "medium",
    versioning: !0,
    priority: "high",
    specialNeeds: ["large-media", "ssd-cache"],
    synonyms: ["photoshop", "psd", "adobe photoshop"],
  },
  {
    id: "illustrator",
    name: "Adobe Illustrator",
    category: "design",
    industries: ["photography", "media", "architecture"],
    avgFileSizeMB: 80,
    dataGrowth: "medium",
    monthlyGrowthGB: 2,
    backupIntervalMin: 60,
    compressibility: "medium",
    dedupBenefit: "medium",
    versioning: !0,
    priority: "high",
    synonyms: ["illustrator", "ai file"],
  },
  {
    id: "lightroom",
    name: "Adobe Lightroom",
    category: "design",
    industries: ["photography", "media"],
    avgFileSizeMB: 40,
    dataGrowth: "very-high",
    monthlyGrowthGB: 15,
    backupIntervalMin: 60,
    compressibility: "low",
    dedupBenefit: "low",
    versioning: !0,
    priority: "high",
    specialNeeds: ["large-media", "ssd-cache"],
    synonyms: ["lightroom", "raw photos"],
  },
  {
    id: "coreldraw",
    name: "CorelDRAW",
    category: "design",
    industries: ["photography", "manufacturing", "retail"],
    avgFileSizeMB: 60,
    dataGrowth: "medium",
    monthlyGrowthGB: 1.5,
    backupIntervalMin: 60,
    compressibility: "medium",
    dedupBenefit: "medium",
    versioning: !0,
    priority: "medium",
    synonyms: ["coreldraw", "corel", "cdr"],
  },
  {
    id: "canva",
    name: "Canva (exports)",
    category: "design",
    industries: ["media", "education", "retail"],
    avgFileSizeMB: 20,
    dataGrowth: "low",
    monthlyGrowthGB: 0.8,
    backupIntervalMin: 1440,
    compressibility: "low",
    dedupBenefit: "low",
    versioning: !1,
    priority: "medium",
    synonyms: ["canva"],
  },
  {
    id: "figma",
    name: "Figma (exports)",
    category: "design",
    industries: ["software", "media"],
    avgFileSizeMB: 30,
    dataGrowth: "medium",
    monthlyGrowthGB: 1.2,
    backupIntervalMin: 1440,
    compressibility: "medium",
    dedupBenefit: "medium",
    versioning: !0,
    priority: "medium",
    synonyms: ["figma"],
  },
  {
    id: "sketch",
    name: "Sketch",
    category: "design",
    industries: ["software", "media"],
    avgFileSizeMB: 40,
    dataGrowth: "medium",
    monthlyGrowthGB: 1.2,
    backupIntervalMin: 1440,
    compressibility: "medium",
    dedupBenefit: "medium",
    versioning: !0,
    priority: "medium",
    synonyms: ["sketch"],
  },
  {
    id: "indesign",
    name: "Adobe InDesign",
    category: "design",
    industries: ["media", "photography"],
    avgFileSizeMB: 120,
    dataGrowth: "medium",
    monthlyGrowthGB: 2.5,
    backupIntervalMin: 60,
    compressibility: "medium",
    dedupBenefit: "medium",
    versioning: !0,
    priority: "high",
    synonyms: ["indesign", "indd"],
  },
  {
    id: "autocad",
    name: "AutoCAD",
    category: "cad",
    industries: ["architecture", "construction", "manufacturing"],
    avgFileSizeMB: 120,
    dataGrowth: "high",
    monthlyGrowthGB: 4,
    backupIntervalMin: 30,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["fast-restore"],
    synonyms: ["autocad", "dwg"],
  },
  {
    id: "revit",
    name: "Autodesk Revit",
    category: "cad",
    industries: ["architecture", "construction"],
    avgFileSizeMB: 800,
    dataGrowth: "very-high",
    monthlyGrowthGB: 8,
    backupIntervalMin: 30,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["fast-restore", "ssd-cache"],
    synonyms: ["revit", "bim", "rvt"],
  },
  {
    id: "sketchup",
    name: "SketchUp",
    category: "cad",
    industries: ["architecture", "construction"],
    avgFileSizeMB: 200,
    dataGrowth: "high",
    monthlyGrowthGB: 3,
    backupIntervalMin: 60,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "high",
    synonyms: ["sketchup", "skp"],
  },
  {
    id: "solidworks",
    name: "SolidWorks",
    category: "cad",
    industries: ["manufacturing", "construction"],
    avgFileSizeMB: 600,
    dataGrowth: "very-high",
    monthlyGrowthGB: 7,
    backupIntervalMin: 30,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["fast-restore"],
    synonyms: ["solidworks", "sldprt"],
  },
  {
    id: "civil3d",
    name: "Civil 3D",
    category: "cad",
    industries: ["construction", "architecture", "government"],
    avgFileSizeMB: 400,
    dataGrowth: "high",
    monthlyGrowthGB: 5,
    backupIntervalMin: 30,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    synonyms: ["civil 3d", "civil3d"],
  },
  {
    id: "staad",
    name: "STAAD.Pro",
    category: "cad",
    industries: ["construction", "architecture"],
    avgFileSizeMB: 150,
    dataGrowth: "medium",
    monthlyGrowthGB: 2,
    backupIntervalMin: 60,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "high",
    synonyms: ["staad", "staad pro"],
  },
  {
    id: "3dsmax",
    name: "3ds Max",
    category: "media-3d",
    industries: ["architecture", "media"],
    avgFileSizeMB: 900,
    dataGrowth: "very-high",
    monthlyGrowthGB: 12,
    backupIntervalMin: 60,
    compressibility: "low",
    dedupBenefit: "medium",
    versioning: !0,
    priority: "high",
    specialNeeds: ["large-media", "ssd-cache"],
    synonyms: ["3ds max", "3dsmax", "max"],
  },
  {
    id: "blender",
    name: "Blender",
    category: "media-3d",
    industries: ["media", "software"],
    avgFileSizeMB: 700,
    dataGrowth: "very-high",
    monthlyGrowthGB: 12,
    backupIntervalMin: 60,
    compressibility: "low",
    dedupBenefit: "medium",
    versioning: !0,
    priority: "high",
    specialNeeds: ["large-media", "ssd-cache"],
    synonyms: ["blender"],
  },
  {
    id: "maya",
    name: "Autodesk Maya",
    category: "media-3d",
    industries: ["media"],
    avgFileSizeMB: 1200,
    dataGrowth: "very-high",
    monthlyGrowthGB: 15,
    backupIntervalMin: 60,
    compressibility: "low",
    dedupBenefit: "medium",
    versioning: !0,
    priority: "high",
    specialNeeds: ["large-media", "ssd-cache"],
    synonyms: ["maya"],
  },
  {
    id: "premiere",
    name: "Adobe Premiere Pro",
    category: "video",
    industries: ["media", "photography"],
    avgFileSizeMB: 5e4,
    dataGrowth: "very-high",
    monthlyGrowthGB: 60,
    backupIntervalMin: 15,
    compressibility: "low",
    dedupBenefit: "low",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["large-media", "ssd-cache", "fast-restore"],
    synonyms: ["premiere", "premiere pro", "adobe premiere"],
  },
  {
    id: "aftereffects",
    name: "Adobe After Effects",
    category: "video",
    industries: ["media"],
    avgFileSizeMB: 8e3,
    dataGrowth: "very-high",
    monthlyGrowthGB: 30,
    backupIntervalMin: 30,
    compressibility: "low",
    dedupBenefit: "low",
    versioning: !0,
    priority: "high",
    specialNeeds: ["large-media", "ssd-cache"],
    synonyms: ["after effects", "ae"],
  },
  {
    id: "davinci",
    name: "DaVinci Resolve",
    category: "video",
    industries: ["media", "photography"],
    avgFileSizeMB: 4e4,
    dataGrowth: "very-high",
    monthlyGrowthGB: 55,
    backupIntervalMin: 15,
    compressibility: "low",
    dedupBenefit: "low",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["large-media", "ssd-cache", "fast-restore"],
    synonyms: ["davinci", "resolve", "davinci resolve"],
  },
  {
    id: "finalcut",
    name: "Final Cut Pro",
    category: "video",
    industries: ["media"],
    avgFileSizeMB: 45e3,
    dataGrowth: "very-high",
    monthlyGrowthGB: 55,
    backupIntervalMin: 15,
    compressibility: "low",
    dedupBenefit: "low",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["large-media", "ssd-cache", "fast-restore"],
    synonyms: ["final cut", "fcpx", "final cut pro"],
  },
  {
    id: "vegas",
    name: "VEGAS Pro",
    category: "video",
    industries: ["media"],
    avgFileSizeMB: 3e4,
    dataGrowth: "very-high",
    monthlyGrowthGB: 45,
    backupIntervalMin: 30,
    compressibility: "low",
    dedupBenefit: "low",
    versioning: !0,
    priority: "high",
    specialNeeds: ["large-media", "ssd-cache"],
    synonyms: ["vegas", "vegas pro", "sony vegas"],
  },
  {
    id: "obs",
    name: "OBS Recordings",
    category: "video",
    industries: ["media", "education"],
    avgFileSizeMB: 6e3,
    dataGrowth: "very-high",
    monthlyGrowthGB: 40,
    backupIntervalMin: 1440,
    compressibility: "low",
    dedupBenefit: "low",
    versioning: !1,
    priority: "medium",
    specialNeeds: ["large-media"],
    synonyms: ["obs", "screen recording"],
  },
  {
    id: "cctv",
    name: "CCTV / NVR Footage",
    category: "video",
    industries: ["retail", "hospitality", "manufacturing", "government"],
    avgFileSizeMB: 1e5,
    dataGrowth: "very-high",
    monthlyGrowthGB: 100,
    backupIntervalMin: 1440,
    compressibility: "low",
    dedupBenefit: "low",
    versioning: !1,
    priority: "high",
    specialNeeds: ["large-media"],
    synonyms: ["cctv", "nvr", "surveillance"],
  },
  {
    id: "audition",
    name: "Adobe Audition",
    category: "audio",
    industries: ["media"],
    avgFileSizeMB: 2e3,
    dataGrowth: "high",
    monthlyGrowthGB: 10,
    backupIntervalMin: 60,
    compressibility: "low",
    dedupBenefit: "low",
    versioning: !0,
    priority: "medium",
    specialNeeds: ["large-media"],
    synonyms: ["audition"],
  },
  {
    id: "protools",
    name: "Pro Tools",
    category: "audio",
    industries: ["media"],
    avgFileSizeMB: 4e3,
    dataGrowth: "high",
    monthlyGrowthGB: 15,
    backupIntervalMin: 60,
    compressibility: "low",
    dedupBenefit: "low",
    versioning: !0,
    priority: "high",
    specialNeeds: ["large-media"],
    synonyms: ["pro tools", "protools"],
  },
  {
    id: "flstudio",
    name: "FL Studio",
    category: "audio",
    industries: ["media"],
    avgFileSizeMB: 1500,
    dataGrowth: "high",
    monthlyGrowthGB: 8,
    backupIntervalMin: 60,
    compressibility: "low",
    dedupBenefit: "low",
    versioning: !0,
    priority: "medium",
    specialNeeds: ["large-media"],
    synonyms: ["fl studio", "fruity loops"],
  },
  {
    id: "vscode",
    name: "VS Code Projects",
    category: "dev",
    industries: ["software"],
    avgFileSizeMB: 500,
    dataGrowth: "medium",
    monthlyGrowthGB: 2,
    backupIntervalMin: 60,
    compressibility: "high",
    dedupBenefit: "very-high",
    versioning: !0,
    priority: "high",
    synonyms: ["vscode", "vs code", "visual studio code"],
  },
  {
    id: "visualstudio",
    name: "Visual Studio",
    category: "dev",
    industries: ["software"],
    avgFileSizeMB: 2e3,
    dataGrowth: "medium",
    monthlyGrowthGB: 3,
    backupIntervalMin: 60,
    compressibility: "high",
    dedupBenefit: "very-high",
    versioning: !0,
    priority: "high",
    synonyms: ["visual studio"],
  },
  {
    id: "jetbrains",
    name: "IntelliJ / JetBrains IDEs",
    category: "dev",
    industries: ["software"],
    avgFileSizeMB: 1500,
    dataGrowth: "medium",
    monthlyGrowthGB: 3,
    backupIntervalMin: 60,
    compressibility: "high",
    dedupBenefit: "very-high",
    versioning: !0,
    priority: "high",
    synonyms: ["intellij", "jetbrains", "pycharm", "webstorm"],
  },
  {
    id: "androidstudio",
    name: "Android Studio",
    category: "dev",
    industries: ["software"],
    avgFileSizeMB: 3e3,
    dataGrowth: "medium",
    monthlyGrowthGB: 4,
    backupIntervalMin: 60,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "high",
    synonyms: ["android studio"],
  },
  {
    id: "git",
    name: "Git Repositories",
    category: "dev",
    industries: ["software"],
    avgFileSizeMB: 800,
    dataGrowth: "high",
    monthlyGrowthGB: 3,
    backupIntervalMin: 15,
    compressibility: "high",
    dedupBenefit: "very-high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["realtime-repo", "fast-restore"],
    synonyms: ["git", "github", "gitlab", "repo", "repository"],
  },
  {
    id: "docker",
    name: "Docker Images / Volumes",
    category: "dev",
    industries: ["software"],
    avgFileSizeMB: 5e3,
    dataGrowth: "high",
    monthlyGrowthGB: 6,
    backupIntervalMin: 60,
    compressibility: "medium",
    dedupBenefit: "very-high",
    versioning: !0,
    priority: "high",
    specialNeeds: ["fast-restore"],
    synonyms: ["docker", "container"],
  },
  {
    id: "k8s",
    name: "Kubernetes Configs",
    category: "dev",
    industries: ["software"],
    avgFileSizeMB: 50,
    dataGrowth: "low",
    monthlyGrowthGB: 0.5,
    backupIntervalMin: 60,
    compressibility: "high",
    dedupBenefit: "very-high",
    versioning: !0,
    priority: "high",
    specialNeeds: ["realtime-repo"],
    synonyms: ["kubernetes", "k8s", "helm"],
  },
  {
    id: "sqlserver",
    name: "SQL Server",
    category: "database",
    industries: ["software", "manufacturing", "accounting", "government"],
    avgFileSizeMB: 8e3,
    dataGrowth: "very-high",
    monthlyGrowthGB: 10,
    backupIntervalMin: 15,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup", "fast-restore"],
    synonyms: ["sql server", "mssql"],
  },
  {
    id: "mysql",
    name: "MySQL",
    category: "database",
    industries: ["software", "retail"],
    avgFileSizeMB: 5e3,
    dataGrowth: "high",
    monthlyGrowthGB: 8,
    backupIntervalMin: 15,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup"],
    synonyms: ["mysql", "mariadb"],
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    category: "database",
    industries: ["software", "healthcare"],
    avgFileSizeMB: 6e3,
    dataGrowth: "high",
    monthlyGrowthGB: 9,
    backupIntervalMin: 15,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup"],
    synonyms: ["postgres", "postgresql"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    category: "database",
    industries: ["software"],
    avgFileSizeMB: 7e3,
    dataGrowth: "high",
    monthlyGrowthGB: 9,
    backupIntervalMin: 15,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup"],
    synonyms: ["mongodb", "mongo"],
  },
  {
    id: "oracledb",
    name: "Oracle Database",
    category: "database",
    industries: ["manufacturing", "government", "healthcare"],
    avgFileSizeMB: 12e3,
    dataGrowth: "very-high",
    monthlyGrowthGB: 12,
    backupIntervalMin: 15,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup", "fast-restore"],
    synonyms: ["oracle db", "oracle database"],
  },
  {
    id: "firebird",
    name: "Firebird",
    category: "database",
    industries: ["accounting", "retail"],
    avgFileSizeMB: 2e3,
    dataGrowth: "medium",
    monthlyGrowthGB: 3,
    backupIntervalMin: 30,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "high",
    specialNeeds: ["db-aware-backup"],
    synonyms: ["firebird"],
  },
  {
    id: "his-emr",
    name: "HIS / EMR System",
    category: "healthcare",
    industries: ["healthcare"],
    avgFileSizeMB: 3e3,
    dataGrowth: "high",
    monthlyGrowthGB: 6,
    backupIntervalMin: 15,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup", "compliance-archive", "immutable"],
    synonyms: ["his", "emr", "ehr", "hospital information system"],
  },
  {
    id: "pacs",
    name: "PACS / DICOM Imaging",
    category: "healthcare",
    industries: ["healthcare"],
    avgFileSizeMB: 3e4,
    dataGrowth: "very-high",
    monthlyGrowthGB: 50,
    backupIntervalMin: 60,
    compressibility: "low",
    dedupBenefit: "medium",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["large-media", "compliance-archive", "immutable"],
    synonyms: ["pacs", "dicom", "radiology", "imaging"],
  },
  {
    id: "lims",
    name: "LIMS (Lab System)",
    category: "healthcare",
    industries: ["healthcare"],
    avgFileSizeMB: 2e3,
    dataGrowth: "high",
    monthlyGrowthGB: 5,
    backupIntervalMin: 30,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup", "compliance-archive"],
    synonyms: ["lims", "lab information"],
  },
  {
    id: "legal-case",
    name: "Legal Case Management",
    category: "legal",
    industries: ["legal"],
    avgFileSizeMB: 800,
    dataGrowth: "medium",
    monthlyGrowthGB: 3,
    backupIntervalMin: 30,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["compliance-archive", "immutable"],
    synonyms: ["case management", "legal case", "practice management"],
  },
  {
    id: "efiling",
    name: "E-Filing / Court Records",
    category: "legal",
    industries: ["legal", "government"],
    avgFileSizeMB: 300,
    dataGrowth: "medium",
    monthlyGrowthGB: 2,
    backupIntervalMin: 60,
    compressibility: "medium",
    dedupBenefit: "medium",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["compliance-archive"],
    synonyms: ["e-filing", "efiling", "court records"],
  },
  {
    id: "moodle",
    name: "Moodle LMS",
    category: "education",
    industries: ["education"],
    avgFileSizeMB: 4e3,
    dataGrowth: "high",
    monthlyGrowthGB: 6,
    backupIntervalMin: 60,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "high",
    specialNeeds: ["db-aware-backup"],
    synonyms: ["moodle", "lms"],
  },
  {
    id: "student-records",
    name: "Student Records System",
    category: "education",
    industries: ["education", "government"],
    avgFileSizeMB: 1500,
    dataGrowth: "medium",
    monthlyGrowthGB: 2.5,
    backupIntervalMin: 60,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["compliance-archive"],
    synonyms: ["student records", "sis"],
  },
  {
    id: "petpooja",
    name: "Petpooja POS",
    category: "pos-retail",
    industries: ["hospitality", "retail"],
    avgFileSizeMB: 200,
    dataGrowth: "medium",
    monthlyGrowthGB: 1.5,
    backupIntervalMin: 30,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup", "fast-restore"],
    synonyms: ["petpooja", "pos"],
  },
  {
    id: "gofrugal",
    name: "GoFrugal POS",
    category: "pos-retail",
    industries: ["retail"],
    avgFileSizeMB: 300,
    dataGrowth: "medium",
    monthlyGrowthGB: 2,
    backupIntervalMin: 30,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup", "fast-restore"],
    synonyms: ["gofrugal"],
  },
  {
    id: "generic-pos",
    name: "POS Software (generic)",
    category: "pos-retail",
    industries: ["retail", "hospitality"],
    avgFileSizeMB: 250,
    dataGrowth: "medium",
    monthlyGrowthGB: 1.5,
    backupIntervalMin: 30,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup", "fast-restore"],
    synonyms: ["pos", "point of sale", "billing software"],
  },
  {
    id: "hotel-pms",
    name: "Hotel PMS",
    category: "hospitality",
    industries: ["hospitality"],
    avgFileSizeMB: 600,
    dataGrowth: "medium",
    monthlyGrowthGB: 2.5,
    backupIntervalMin: 30,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup", "fast-restore"],
    synonyms: ["hotel pms", "property management", "opera pms"],
  },
  {
    id: "arcgis",
    name: "ArcGIS",
    category: "gis",
    industries: ["government", "construction"],
    avgFileSizeMB: 5e3,
    dataGrowth: "high",
    monthlyGrowthGB: 8,
    backupIntervalMin: 60,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "high",
    specialNeeds: ["large-media"],
    synonyms: ["arcgis", "esri"],
  },
  {
    id: "qgis",
    name: "QGIS",
    category: "gis",
    industries: ["government", "construction"],
    avgFileSizeMB: 3e3,
    dataGrowth: "high",
    monthlyGrowthGB: 6,
    backupIntervalMin: 60,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "high",
    specialNeeds: ["large-media"],
    synonyms: ["qgis"],
  },
  {
    id: "vmware",
    name: "VMware VM Images",
    category: "database",
    industries: ["software", "manufacturing", "government", "healthcare"],
    avgFileSizeMB: 6e4,
    dataGrowth: "very-high",
    monthlyGrowthGB: 20,
    backupIntervalMin: 1440,
    compressibility: "medium",
    dedupBenefit: "very-high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["vm-snapshot", "fast-restore"],
    synonyms: ["vmware", "vm", "virtual machine", "esxi"],
  },
  {
    id: "hyperv",
    name: "Hyper-V VM Images",
    category: "database",
    industries: ["software", "government"],
    avgFileSizeMB: 5e4,
    dataGrowth: "very-high",
    monthlyGrowthGB: 18,
    backupIntervalMin: 1440,
    compressibility: "medium",
    dedupBenefit: "very-high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["vm-snapshot", "fast-restore"],
    synonyms: ["hyper-v", "hyperv"],
  },
  {
    id: "custom-inhouse",
    name: "Custom In-house Software",
    category: "other",
    industries: ["software", "manufacturing", "other"],
    avgFileSizeMB: 1e3,
    dataGrowth: "medium",
    monthlyGrowthGB: 3,
    backupIntervalMin: 30,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "high",
    specialNeeds: ["db-aware-backup"],
    synonyms: ["custom software", "in-house", "bespoke"],
  },
  {
    id: "website-cpanel",
    name: "Website / cPanel",
    category: "other",
    industries: ["software", "retail", "other"],
    avgFileSizeMB: 2e3,
    dataGrowth: "medium",
    monthlyGrowthGB: 3,
    backupIntervalMin: 1440,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "high",
    specialNeeds: ["db-aware-backup"],
    synonyms: ["website", "cpanel", "wordpress"],
  },
  {
    id: "xero",
    name: "Xero",
    category: "finance",
    industries: ["accounting"],
    avgFileSizeMB: 50,
    dataGrowth: "low",
    monthlyGrowthGB: 0.6,
    backupIntervalMin: 60,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "high",
    synonyms: ["xero"],
  },
  {
    id: "tally-erp9",
    name: "Tally ERP 9",
    category: "finance",
    industries: ["accounting", "retail"],
    avgFileSizeMB: 180,
    dataGrowth: "medium",
    monthlyGrowthGB: 1.3,
    backupIntervalMin: 30,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup"],
    synonyms: ["tally erp 9", "tally 9"],
  },
  {
    id: "gsheets",
    name: "Google Sheets (exports)",
    category: "office",
    industries: ["accounting", "other", "education"],
    avgFileSizeMB: 10,
    dataGrowth: "low",
    monthlyGrowthGB: 0.4,
    backupIntervalMin: 1440,
    compressibility: "high",
    dedupBenefit: "very-high",
    versioning: !0,
    priority: "medium",
    synonyms: ["google sheets", "sheets"],
  },
  {
    id: "onedrive",
    name: "OneDrive / SharePoint",
    category: "office",
    industries: ["other", "government", "education"],
    avgFileSizeMB: 20,
    dataGrowth: "medium",
    monthlyGrowthGB: 1.5,
    backupIntervalMin: 1440,
    compressibility: "high",
    dedupBenefit: "very-high",
    versioning: !0,
    priority: "high",
    synonyms: ["onedrive", "sharepoint"],
  },
  {
    id: "aftershot",
    name: "Capture One",
    category: "design",
    industries: ["photography", "media"],
    avgFileSizeMB: 45,
    dataGrowth: "very-high",
    monthlyGrowthGB: 14,
    backupIntervalMin: 60,
    compressibility: "low",
    dedupBenefit: "low",
    versioning: !0,
    priority: "high",
    specialNeeds: ["large-media", "ssd-cache"],
    synonyms: ["capture one", "phase one"],
  },
  {
    id: "affinity",
    name: "Affinity Suite",
    category: "design",
    industries: ["photography", "media"],
    avgFileSizeMB: 120,
    dataGrowth: "medium",
    monthlyGrowthGB: 2.5,
    backupIntervalMin: 60,
    compressibility: "low",
    dedupBenefit: "medium",
    versioning: !0,
    priority: "medium",
    synonyms: ["affinity", "affinity photo", "affinity designer"],
  },
  {
    id: "raw-photos",
    name: "RAW Photo Library",
    category: "design",
    industries: ["photography"],
    avgFileSizeMB: 35,
    dataGrowth: "very-high",
    monthlyGrowthGB: 25,
    backupIntervalMin: 60,
    compressibility: "low",
    dedupBenefit: "low",
    versioning: !1,
    priority: "critical",
    specialNeeds: ["large-media", "ssd-cache"],
    synonyms: ["raw", "raw files", "cr2", "nef", "wedding photos"],
  },
  {
    id: "inventor",
    name: "Autodesk Inventor",
    category: "cad",
    industries: ["manufacturing"],
    avgFileSizeMB: 500,
    dataGrowth: "high",
    monthlyGrowthGB: 6,
    backupIntervalMin: 30,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["fast-restore"],
    synonyms: ["inventor"],
  },
  {
    id: "catia",
    name: "CATIA",
    category: "cad",
    industries: ["manufacturing"],
    avgFileSizeMB: 700,
    dataGrowth: "very-high",
    monthlyGrowthGB: 8,
    backupIntervalMin: 30,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["fast-restore"],
    synonyms: ["catia"],
  },
  {
    id: "plc",
    name: "PLC / SCADA Configs",
    category: "cad",
    industries: ["manufacturing"],
    avgFileSizeMB: 100,
    dataGrowth: "low",
    monthlyGrowthGB: 0.8,
    backupIntervalMin: 60,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["immutable"],
    synonyms: ["plc", "scada"],
  },
  {
    id: "camtasia",
    name: "Camtasia",
    category: "video",
    industries: ["education", "media"],
    avgFileSizeMB: 5e3,
    dataGrowth: "high",
    monthlyGrowthGB: 20,
    backupIntervalMin: 60,
    compressibility: "low",
    dedupBenefit: "low",
    versioning: !0,
    priority: "medium",
    specialNeeds: ["large-media"],
    synonyms: ["camtasia"],
  },
  {
    id: "raw-video",
    name: "RAW / ProRes Footage",
    category: "video",
    industries: ["media", "photography"],
    avgFileSizeMB: 12e4,
    dataGrowth: "very-high",
    monthlyGrowthGB: 120,
    backupIntervalMin: 60,
    compressibility: "low",
    dedupBenefit: "low",
    versioning: !1,
    priority: "critical",
    specialNeeds: ["large-media", "ssd-cache"],
    synonyms: ["prores", "raw video", "footage", "wedding video"],
  },
  {
    id: "redis",
    name: "Redis",
    category: "database",
    industries: ["software"],
    avgFileSizeMB: 2e3,
    dataGrowth: "medium",
    monthlyGrowthGB: 3,
    backupIntervalMin: 30,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "high",
    specialNeeds: ["db-aware-backup"],
    synonyms: ["redis"],
  },
  {
    id: "sqlite",
    name: "SQLite Databases",
    category: "database",
    industries: ["software", "other"],
    avgFileSizeMB: 500,
    dataGrowth: "medium",
    monthlyGrowthGB: 1.5,
    backupIntervalMin: 60,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "high",
    specialNeeds: ["db-aware-backup"],
    synonyms: ["sqlite"],
  },
  {
    id: "jenkins",
    name: "CI/CD Artifacts (Jenkins)",
    category: "dev",
    industries: ["software"],
    avgFileSizeMB: 3e3,
    dataGrowth: "high",
    monthlyGrowthGB: 5,
    backupIntervalMin: 1440,
    compressibility: "high",
    dedupBenefit: "very-high",
    versioning: !0,
    priority: "medium",
    synonyms: ["jenkins", "ci/cd", "build artifacts"],
  },
  {
    id: "dental",
    name: "Dental Practice Software",
    category: "healthcare",
    industries: ["healthcare"],
    avgFileSizeMB: 2e3,
    dataGrowth: "high",
    monthlyGrowthGB: 4,
    backupIntervalMin: 30,
    compressibility: "medium",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup", "compliance-archive"],
    synonyms: ["dental", "dentrix"],
  },
  {
    id: "pharmacy",
    name: "Pharmacy Management",
    category: "healthcare",
    industries: ["healthcare", "retail"],
    avgFileSizeMB: 800,
    dataGrowth: "medium",
    monthlyGrowthGB: 2.5,
    backupIntervalMin: 30,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["db-aware-backup", "compliance-archive"],
    synonyms: ["pharmacy", "chemist"],
  },
  {
    id: "tax-software",
    name: "Tax / Compliance Software",
    category: "finance",
    industries: ["accounting", "legal"],
    avgFileSizeMB: 300,
    dataGrowth: "medium",
    monthlyGrowthGB: 1.5,
    backupIntervalMin: 60,
    compressibility: "high",
    dedupBenefit: "high",
    versioning: !0,
    priority: "critical",
    specialNeeds: ["compliance-archive"],
    synonyms: ["tax software", "gst", "income tax"],
  },
];
export const NV = Object.fromEntries(hC.map((n) => [n.id, n]));
export const UV = [
  "Local computers",
  "NAS",
  "External HDD",
  "Cloud (Drive/Dropbox/OneDrive)",
  "On-prem server",
  "Virtual machines",
  "Hybrid",
];
export const GV = [
  { id: "1-5", label: "1–5" },
  { id: "6-20", label: "6–20" },
  { id: "21-100", label: "21–100" },
  { id: "100+", label: "100+" },
];
export const _V = [
  {
    id: "recreate",
    label: "I can recreate it",
    desc: "Minor inconvenience if lost",
  },
  {
    id: "few-days",
    label: "Lose a few days of work",
    desc: "Painful but survivable",
  },
  {
    id: "business-stops",
    label: "Business stops",
    desc: "Operations halt without this data",
  },
  {
    id: "legal",
    label: "Legal / compliance requirement",
    desc: "We are legally required to retain it",
  },
];
export const IC = [
  {
    id: "accounting",
    label: "Accounting & Finance",
    icon: "Calculator",
    categories: ["finance", "erp", "office", "email"],
  },
  {
    id: "architecture",
    label: "Architecture & CAD",
    icon: "Ruler",
    categories: ["cad", "design", "media-3d", "office"],
  },
  {
    id: "healthcare",
    label: "Healthcare",
    icon: "HeartPulse",
    categories: ["healthcare", "office", "email", "database"],
  },
  {
    id: "legal",
    label: "Legal",
    icon: "Scale",
    categories: ["legal", "office", "email"],
  },
  {
    id: "manufacturing",
    label: "Manufacturing",
    icon: "Factory",
    categories: ["erp", "cad", "database", "office"],
  },
  {
    id: "photography",
    label: "Photography",
    icon: "Camera",
    categories: ["design", "video", "office"],
  },
  {
    id: "education",
    label: "Education",
    icon: "GraduationCap",
    categories: ["education", "office", "email"],
  },
  {
    id: "software",
    label: "Software Development",
    icon: "Code2",
    categories: ["dev", "database", "office"],
  },
  {
    id: "media",
    label: "Media & Video",
    icon: "Clapperboard",
    categories: ["video", "audio", "media-3d", "design"],
  },
  {
    id: "construction",
    label: "Construction",
    icon: "HardHat",
    categories: ["cad", "erp", "office"],
  },
  {
    id: "government",
    label: "Government",
    icon: "Landmark",
    categories: ["office", "gis", "database", "email"],
  },
  {
    id: "retail",
    label: "Retail & POS",
    icon: "ShoppingCart",
    categories: ["pos-retail", "finance", "office"],
  },
  {
    id: "hospitality",
    label: "Hospitality",
    icon: "UtensilsCrossed",
    categories: ["hospitality", "pos-retail", "office"],
  },
  {
    id: "other",
    label: "Other / General",
    icon: "Boxes",
    categories: ["office", "email", "database"],
  },
];
export const Rb = {
  finance: "Finance & Accounting",
  erp: "ERP & Business Suites",
  design: "Design & Creative",
  cad: "CAD & Engineering",
  video: "Video Editing",
  audio: "Audio Production",
  dev: "Development Tools",
  database: "Databases",
  office: "Office & Documents",
  email: "Email & Communication",
  healthcare: "Healthcare Systems",
  legal: "Legal Software",
  education: "Education & LMS",
  "pos-retail": "POS & Retail",
  hospitality: "Hospitality",
  "media-3d": "3D & Motion",
  gis: "GIS & Mapping",
  other: "Other / Generic",
};
export const WV = { "1-5": 1.5, "6-20": 8, "21-100": 40, "100+": 120 };
export const ZV = { recreate: 2, "few-days": 3, "business-stops": 4, legal: 5 };
export const Yj = [250, 500, 1e3, 2e3, 5e3, 1e4, 2e4, 5e4];
function $V(n) {
  for (const o of Yj) if (n <= o) return o;
  return Math.ceil(n / 1e4) * 1e4;
}
export function XV(n) {
  const o = n * 0.5,
    c = [125, ...Yj].sort((h, u) => h - u);
  let s = c[0];
  for (const h of c) h <= n && Math.abs(h - o) <= Math.abs(s - o) && (s = h);
  return Math.min(s, n);
}
export function Qb(n) {
  if (n >= 1e3) {
    const o = n / 1e3;
    return `${Number.isInteger(o) ? o : o.toFixed(1)} TB`;
  }
  return `${n} GB`;
}
export function Jj(n) {
  if (n >= 1440) return "Daily";
  if (n >= 60) {
    const o = n / 60;
    return o === 1 ? "Hourly" : `Every ${o} Hours`;
  }
  return `Every ${n} Minutes`;
}
export function KV(n) {
  return n.softwareIds.map((o) => NV[o]).filter(Boolean);
}
export function C1(n, o) {
  return n.some((c) => c.specialNeeds?.includes(o));
}
export function cq(n) {
  return IC.find((o) => o.id === n)?.label ?? "General Business";
}
export function lq(n) {
  const o = KV(n),
    c = n.customSoftware.length,
    s = o.reduce((Me, Lo) => Me + Lo.monthlyGrowthGB, 0) + c * 2,
    h = WV[n.teamSize],
    u = n.dataLocations,
    f =
      u.includes("Virtual machines") ||
      u.includes("On-prem server") ||
      u.includes("NAS") ||
      u.includes("Hybrid")
        ? 1.3
        : 1,
    m = Math.max(1, Math.round(s * h * f)),
    M = m * 3 + 12 * m,
    g = $V(M),
    b = XV(g);
  let L = o.length
    ? Math.min(
        ...o
          .filter((Me) => !Me.specialNeeds?.includes("realtime-repo"))
          .map((Me) => Me.backupIntervalMin)
          .concat(o.length ? [] : [1440]),
      )
    : 1440;
  (Number.isFinite(L) ||
    (L = o.length ? Math.min(...o.map((Me) => Me.backupIntervalMin)) : 1440),
    (n.criticality === "business-stops" || n.criticality === "legal") &&
      (L = Math.min(L, 30)),
    n.criticality === "recreate" && (L = Math.max(L, 60)));
  const A = ["legal", "healthcare", "government"].includes(n.industry),
    C = n.criticality === "legal",
    I = A || C,
    R =
      ["media", "photography"].includes(n.industry) ||
      o.some((Me) => ["video", "audio", "media-3d"].includes(Me.category));
  let B = 90,
    F = 30;
  I ? ((B = 2555), (F = 365)) : R ? ((B = 180), (F = 180)) : (F = 90);
  const D = o.some((Me) => Me.priority === "critical"),
    G = C1(o, "db-aware-backup"),
    N = C1(o, "vm-snapshot") || u.includes("Virtual machines"),
    Q = C1(o, "realtime-repo"),
    le = C1(o, "large-media") || C1(o, "ssd-cache"),
    me = C1(o, "fast-restore"),
    de = C1(o, "immutable") || C1(o, "compliance-archive"),
    ae = o.filter((Me) => Me.compressibility === "low").length,
    te = o.filter((Me) => Me.compressibility === "high").length;
  let ie;
  ae > te && ae > 0 ? (ie = "Low") : te > ae ? (ie = "High") : (ie = "Medium");
  const $ = o.some((Me) => Me.dedupBenefit === "very-high"),
    fe = o.some((Me) => Me.dedupBenefit === "high");
  let ne;
  $ ? (ne = "Very High") : fe ? (ne = "High") : (ne = "Medium");
  let ce = "Incremental Forever";
  le
    ? (ce = "Incremental Forever (SSD-cached)")
    : G && (ce = "Incremental + DB-aware Snapshots");
  let T;
  n.teamSize === "100+" || I || g > 5e3
    ? (T = "Enterprise")
    : g <= 250 && n.teamSize === "1-5" && !D
      ? (T = "Starter")
      : (T = "Business");
  let Z;
  D && (n.criticality === "business-stops" || n.criticality === "legal")
    ? (Z = "High")
    : o.length > 0 &&
        o.every((Me) => Me.priority === "medium") &&
        n.criticality === "recreate"
      ? (Z = "Low")
      : (Z = "Medium");
  const W = T !== "Starter" || I || D,
    z = !0;
  let V = "Weekly";
  I
    ? (V = "Monthly (air-gapped)")
    : R || g >= 5e3
      ? (V = "Monthly")
      : T === "Starter" && (V = "Optional");
  const se = u.length === 1 && u[0] === "External HDD",
    ue =
      u.length > 0 &&
      u.every((Me) => Me === "Local computers" || Me === "External HDD"),
    pe = {
      ransomware: z ? 5 : 3,
      hardwareFailure: 5,
      accidentalDelete: 5,
      powerFailure: 5,
      fire: W && V.startsWith("Monthly") ? 5 : 4,
      flood: W && V.startsWith("Monthly") ? 5 : 4,
    };
  se
    ? ((pe.fire = 2), (pe.flood = 2), (pe.hardwareFailure = 3))
    : ue && ((pe.fire = 3), (pe.flood = 3));
  const ye = [];
  (G &&
    ye.push({
      label: "Database Backup",
      value: "Every 15 Minutes (app-consistent)",
    }),
    N && ye.push({ label: "VM Snapshot", value: "Daily" }),
    Q && ye.push({ label: "Repository Sync", value: "Real-time" }),
    le
      ? ye.push({ label: "SSD Cache", value: "Recommended + Fast Restore" })
      : me && ye.push({ label: "Fast Restore", value: "Enabled" }),
    de && ye.push({ label: "Compliance Archive", value: "WORM / Immutable" }));
  const xe = [];
  xe.push(cq(n.industry));
  for (const Me of o.slice(0, 6)) xe.push(Me.name);
  for (const Me of n.customSoftware.slice(0, 3)) xe.push(Me);
  const ge = QV({
      swList: o,
      monthlyGrowthGB: m,
      intervalMin: L,
      compression: ie,
      dedup: ne,
      isMedia: R,
      hasDb: G,
      hasVm: N,
      hasGit: Q,
      needsCompliance: I,
      recommendedStorageGB: g,
    }),
    Ce = ZV[n.criticality];
  return {
    profile: {
      businessType:
        n.industry === "other"
          ? "General Business"
          : `${cq(n.industry)} Business`,
      detectedFrom: xe,
      riskLevel: Z,
      monthlyGrowthGB: m,
      criticalityStars: Ce,
    },
    plan: {
      tier: T,
      minStorageGB: b,
      recommendedStorageGB: g,
      backupInterval: Jj(L),
      backupType: ce,
      retentionDays: B,
      versioningDays: F,
      encryption: "AES-256",
      compression: ie,
      dedup: ne,
      verification: "Automated integrity check + monthly test restore",
      cloudReplication: W,
      offlineCopy: V,
      immutableStorage: z,
      extras: ye,
    },
    drScores: pe,
    reasoning: ge,
    source: "guided",
  };
}
export function QV(n) {
  const o = [],
    c = n.swList.map((s) => s.name);
  return (
    o.push(
      `Based on your ${c.length ? c.slice(0, 3).join(", ") + (c.length > 3 ? " and more" : "") : "workflow"}, we estimate about ${n.monthlyGrowthGB} GB of new data per month — so we provision ${Qb(n.recommendedStorageGB)} to cover 12+ months of growth without re-provisioning.`,
    ),
    n.isMedia
      ? o.push(
          `Media projects (video/photo/3D) are large and already compressed, so we recommend ${n.compression.toLowerCase()} compression with SSD-cached incremental-forever backups for fast open/restore of active projects.`,
        )
      : n.dedup === "Very High" &&
        o.push(
          `Your files (spreadsheets, documents, code, email) deduplicate extremely well — ${n.dedup.toLowerCase()} deduplication and ${n.compression.toLowerCase()} compression will dramatically shrink stored size and cost.`,
        ),
    n.hasDb &&
      o.push(
        "Because you run live databases/accounting or POS software, we use application-consistent, DB-aware snapshots every 15 minutes so a restore is never corrupt or mid-transaction.",
      ),
    n.hasVm
      ? o.push(
          "Virtual machines are captured as daily image-level snapshots so an entire server can be spun up in minutes, not rebuilt from scratch.",
        )
      : n.hasGit &&
        o.push(
          "Source repositories are mirrored in real-time — every commit is protected the moment it lands, with instant rollback to any point.",
        ),
    o.push(
      `Given how critical this data is, we set the backup cadence to ${Jj(n.intervalMin)}${n.needsCompliance ? " and retain everything for 7 years in immutable, WORM storage to satisfy compliance/legal requirements." : ", with immutable storage so ransomware cannot alter or delete your restore points."}`,
    ),
    o.slice(0, 5)
  );
}
export const YV = {
  accounting: [
    "account",
    "finance",
    "bookkeep",
    "tax",
    "audit",
    "ca ",
    "chartered",
  ],
  architecture: [
    "architect",
    "cad",
    "bim",
    "revit",
    "drafting",
    "interior design",
  ],
  healthcare: [
    "hospital",
    "clinic",
    "doctor",
    "dental",
    "pharma",
    "medical",
    "patient",
    "lab",
    "diagnostic",
  ],
  legal: ["law", "legal", "attorney", "advocate", "court", "litigation"],
  manufacturing: [
    "manufactur",
    "factory",
    "production",
    "plant",
    "erp",
    "assembly",
  ],
  photography: [
    "photograph",
    "photo studio",
    "wedding photo",
    "raw",
    "lightroom",
  ],
  education: [
    "school",
    "college",
    "university",
    "education",
    "student",
    "teach",
    "lms",
    "training",
  ],
  software: [
    "software",
    "developer",
    "coding",
    "startup",
    "saas",
    "dev team",
    "programmer",
    "it company",
  ],
  media: [
    "video",
    "editor",
    "editing",
    "film",
    "youtube",
    "media",
    "post production",
    "animation",
    "vfx",
    "wedding video",
  ],
  construction: [
    "construction",
    "civil",
    "contractor",
    "builder",
    "infrastructure",
    "site",
  ],
  government: ["government", "municipal", "public sector", "govt", "ministry"],
  retail: [
    "retail",
    "shop",
    "store",
    "pos",
    "billing",
    "supermarket",
    "kirana",
  ],
  hospitality: ["hotel", "restaurant", "cafe", "hospitality", "resort", "food"],
  other: [],
};
export function JV(n) {
  return {
    industry: "other",
    softwareIds: [],
    customSoftware: [n.substring(0, 50)],
    dataLocations: ["Local computers"],
    teamSize: "1-5",
    criticality: "few-days",
  };
}
